# starship config

add_newline = true

[character]
success_symbol = "[âœ](bold yellow)"

[battery]
format = "[$symbol$percentage]($style) "
full_symbol = "ğŸ”‹ "
discharging_symbol = "âš¡ï¸ "
charging_symbol = "ğŸ’€ "

[[battery.display]]
threshold = 100
style = "bold yellow"

[rust]
format = "via [$symbol($version )]($style)"
symbol = "ğŸ¢ "
style = "bold yellow"

